### ISSUE TITLE
Computing requirements for viralcomplete.py

### ISSUE THREAD

**Issue by AlbertRockG** [ablab/viralComplete#1]
Hi there, 

I was computing with viralcomplete.py on my laptop, but at BLAST running step, it runs out of memory and the OS killed the process. So I want to know what are the computing requirements for the script. My laptop has 16 Gb Ram, Core i7 with 8 threads.

**Comment by Dmitry-Antipov** [comment]
Hi,
That's strange, BLAST is not very memory consuming tool.

How many threads you used? Does it run  out of memory with one thread only?

**Comment by AlbertRockG** [comment]
Here is the script I used : 

./viralcomplete.py -f /home/uaclstm/Documents/all/unmapped_fastq_files/BD_CONTIGSVIRAL/contigs.fasta -o /home/uaclstm/Documents/all/unmapped_fastq_files/BD_VIRALCOMPLETE_RESULTS/ -t 8

**Comment by AlbertRockG** [comment]
I just tried it again. And in the meantime I have been monitoring the various processes that my computer was running. I then noticed that after running blastp, Python3 started consuming all the Ram. As a result, the operating system killed the process.

**Comment by Dmitry-Antipov** [comment]
So, with one thread there were also memory issues?

Can you share contigs file with us for debug?

**Comment by AlbertRockG** [comment]
Yes, even with one thread. Sorry, I can't.

**Comment by Dmitry-Antipov** [comment]
That is not a normal situation but some bug, likely in parsing blast results XML. We'll update if we found it.

**Comment by AlbertRockG** [comment]
Hi Dmitry! 
Sorry for bothering you. There are no bugs with the code. I messed up with the contigs that's why. My deep apologies.
